In [7]:
from keys import *
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.data.historical.stock import StockHistoricalDataClient
from datetime import datetime
import pandas as pd

start = datetime(2015, 1, 1)
end = datetime(2023, 1, 1)

trading_client = StockHistoricalDataClient(api_key=API_KEY, secret_key=SECRET_KEY)

def get_price_hist(stock, start: datetime, end: datetime):

    request_params = StockBarsRequest(
        symbol_or_symbols=stock,
        timeframe=TimeFrame.Day,
        start=start,
        end=end
    )

    stock_hist = trading_client.get_stock_bars(request_params)
    df = stock_hist.df
    df.reset_index(inplace=True)
    df.set_index('timestamp', inplace=True)
    df.drop(['volume', 'trade_count', 'vwap'],axis = 1, inplace=True)

    return df

market_data_spy = get_price_hist('SPY', start=start, end=end)
market_data_efa = get_price_hist('EFA', start=start, end=end)
market_data_bnd = get_price_hist('BND', start=start, end=end)
market_data_vnq = get_price_hist('VNQ', start=start, end=end)
market_data_gsg = get_price_hist('GSG', start=start, end=end)

df = pd.concat([market_data_spy, market_data_bnd, market_data_efa, market_data_gsg, market_data_vnq], axis=1)
df

,symbol,open,high,low,close,symbol,open,high,low,close,...,symbol,open,high,low,close,symbol,open,high,low,close
timestamp,,,,,,,,,,,,,,,,,,,,,
2015-12-01 05:00:00+00:00,SPY,209.440,210.8200,209.1100,210.680,BND,81.17,81.4500,81.1350,81.44,...,GSG,15.570,15.6800,15.5001,15.58,VNQ,79.500,80.520,79.4200,80.49
2015-12-02 05:00:00+00:00,SPY,210.615,211.0000,208.2300,208.529,BND,81.40,81.4099,81.2828,81.34,...,GSG,15.450,15.5400,15.1670,15.21,VNQ,80.260,80.370,78.7300,78.85
2015-12-03 05:00:00+00:00,SPY,208.830,209.1500,204.7511,205.610,BND,81.15,81.1500,80.6800,80.71,...,GSG,15.270,15.5900,15.2000,15.43,VNQ,78.730,78.850,77.4000,77.61
2015-12-04 05:00:00+00:00,SPY,206.080,209.9700,205.9300,209.620,BND,80.87,81.0400,80.7900,81.03,...,GSG,15.300,15.4299,15.2560,15.35,VNQ,77.680,79.290,77.6500,79.09
2015-12-07 05:00:00+00:00,SPY,209.230,209.7295,207.2000,208.350,BND,81.06,81.2900,81.0374,81.17,...,GSG,15.070,15.1000,14.7000,14.77,VNQ,78.960,79.190,78.5200,78.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23 05:00:00+00:00,SPY,379.650,383.0600,378.0300,382.910,BND,72.50,72.6200,72.4500,72.53,...,GSG,20.940,21.1300,20.7800,21.09,VNQ,81.760,82.765,81.4000,82.74
2022-12-27 05:00:00+00:00,SPY,382.790,383.1500,379.6500,381.400,BND,72.13,72.2300,71.9600,71.97,...,GSG,20.860,21.4200,20.6500,21.24,VNQ,82.712,82.970,81.9800,82.71
2022-12-28 05:00:00+00:00,SPY,381.330,383.3900,376.4200,376.660,BND,72.12,72.1789,71.8600,71.87,...,GSG,21.080,21.1000,20.7700,21.04,VNQ,82.880,83.270,81.1800,81.30
2022-12-29 05:00:00+00:00,SPY,379.630,384.3500,379.0800,383.440,BND,71.97,72.1671,71.9500,72.14,...,GSG,20.800,21.0100,20.7499,20.99,VNQ,81.870,83.260,81.6300,83.08
2022-12-30 05:00:00+00:00,SPY,380.640,382.5800,378.4300,382.430,BND,71.98,72.0800,71.8000,71.84,...,GSG,20.979,21.2550,20.9100,21.23,VNQ,82.480,82.850,81.5036,82.48

In [18]:
df.loc[df.index == '2016-01-04 05:00:00+00:00']

                              low   low    low    low      low
timestamp
2016-01-04 05:00:00+00:00  198.59  80.7  57.15  14.04  78.0361

In [5]:
df.loc[df['timestamp']]

ValueError: Cannot index with multidimensional key