In [15]:
from ib_insync import *
import nest_asyncio
nest_asyncio.apply()

In [16]:
import pandas as pd

ib = IB()

ib.connect('127.0.0.1', 7497, clientId=1)

contract = Forex('EURUSD')

bars = ib.reqHistoricalData(contract, endDateTime='',durationStr='30 D', barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)

df = pd.DataFrame(bars)
df

,date,open,high,low,close,volume,average,barCount
0,2022-10-16 17:15:00,0.97195,0.97260,0.97195,0.97245,-1.0,-1.0,-1
1,2022-10-16 18:00:00,0.97245,0.97385,0.97235,0.97325,-1.0,-1.0,-1
2,2022-10-16 19:00:00,0.97325,0.97435,0.97310,0.97400,-1.0,-1.0,-1
3,2022-10-16 20:00:00,0.97400,0.97510,0.97370,0.97460,-1.0,-1.0,-1
4,2022-10-16 21:00:00,0.97460,0.97510,0.97390,0.97455,-1.0,-1.0,-1
...,...,...,...,...,...,...,...,...
715,2022-11-25 12:00:00,1.04015,1.04095,1.03985,1.04060,-1.0,-1.0,-1
716,2022-11-25 13:00:00,1.04060,1.04060,1.03970,1.04020,-1.0,-1.0,-1
717,2022-11-25 14:00:00,1.04020,1.04150,1.03995,1.04120,-1.0,-1.0,-1
718,2022-11-25 15:00:00,1.04120,1.04145,1.04085,1.04090,-1.0,-1.0,-1
719,2022-11-25 16:00:00,1.04090,1.04110,1.03855,1.03965,-1.0,-1.0,-1

In [17]:
second_contract = Stock('AAPL', 'SMART', 'USD')

data = ib.reqContractDetails(second_contract)

# datas = pd.DataFrame(data)
data

[ContractDetails(contract=Contract(secType='STK', conId=265598, symbol='AAPL', exchange='SMART', primaryExchange='NASDAQ', currency='USD', localSymbol='AAPL', tradingClass='NMS'), marketName='NMS', minTick=0.01, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AON,AVGCOST,BASKET,BENCHPX,CASHQTY,COND,CONDORDER,DARKONLY,DARKPOLL,DAY,DEACT,DEACTDIS,DEACTEOD,DIS,DUR,GAT,GTC,GTD,GTT,HID,IBKRATS,ICE,IMB,IOC,LIT,LMT,LOC,MIDPX,MIT,MKT,MOC,MTL,NGCOMB,NODARK,NONALGO,OCA,OPG,OPGREROUT,PEGBENCH,PEGMID,POSTATS,POSTONLY,PREOPGRTH,PRICECHK,REL,REL2MID,RELPCTOFS,RPI,RTH,SCALE,SCALEODD,SCALERST,SIZECHK,SMARTSTG,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,SWEEP,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='SMART,AMEX,NYSE,CBOE,PHLX,ISE,CHX,ARCA,ISLAND,DRCTEDGE,BEX,BATS,EDGEA,CSFBALGO,JEFFALGO,BYX,IEX,EDGX,FOXRIVER,PEARL,NYSENAT,LTSE,MEMX,PSX', priceMagnifier=1, underConId=0, longName='APPLE INC', contractMonth='', industry='Technology', category='Computers', subcategory='Computers', timeZoneId='US/Eastern', tradingHours='20221126:CLOSED;20221127:CLOSED;20221128:0400-20221128:2000;20221129:0400-20221129:2000;20221130:0400-20221130:2000;20221201:0400-20221201:2000', liquidHours='20221126:CLOSED;20221127:CLOSED;20221128:0930-20221128:1600;20221129:0930-20221129:1600;20221130:0930-20221130:1600;20221201:0930-20221201:1600', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=1, underSymbol='', underSecType='', marketRuleIds='26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26', secIdList=[TagValue(tag='ISIN', value='US0378331005')], realExpirationDate='', lastTradeTime='', stockType='COMMON', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=100.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')]

In [18]:
contracts = [cd.contract for cd in data]

util.df(contracts)

,secType,conId,symbol,lastTradeDateOrContractMonth,strike,right,multiplier,exchange,primaryExchange,currency,localSymbol,tradingClass,includeExpired,secIdType,secId,description,issuerId,comboLegsDescrip,comboLegs,deltaNeutralContract
0,STK,265598,AAPL,,0.0,,,SMART,NASDAQ,USD,AAPL,NMS,False,,,,,,[],None

Peer closed connection.
Peer closed connection.